### DISCUSSION TITLE
how to set up a distributed RisingWave cluster on k8s or on host.

### DISCUSSION THREAD

**Discussion by XuankuF** [risingwavelabs/risingwave#9431] [Q&A] [answered]
I follow the [docs](https://www.risingwave.dev/docs/current/risingwave-kubernetes) to set up RisingWave on k8s, but it's only one compute/compactor pod and seem not a distributed cluster.

**Comment by xxchan** [comment, marked as answer]
```
    replicas:
      meta: 1
      frontend: 1
      compute: 1
      compactor: 1
```

There is a section called replicas where you can specify the number of each type of node.
