### ISSUE TITLE
chore: utilize workspace dependencies for our own crates

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#11268]
```toml
risingwave_meta = { path = "../../../meta" }
risingwave_rt = { path = "../../../utils/runtime" }
```

is ugly and hard to write.

change to:

```toml
risingwave_meta.workspace = true
risingwave_rt.workspace = true
```
