### ISSUE TITLE
bug(ci): multi-version tikv-jemalloc-sys break docker pipeline

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#12315]
### Describe the bug

RisingWave got 2 version of `tikv-jemalloc-sys` built in docker pipeline. And it breaks CI.

```bash
cp ./target/release/build/tikv-jemalloc-sys-*/out/build/bin/jeprof /risingwave/bin/
```

<img width="224" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/3bdbde7e-1b1b-43b3-a653-ad30f74b67b0">

### Error message/log

```text
<img width="1055" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/21c68b59-7d1b-47a8-82a9-df8f30f9bb03">
```

**Comment by MrCroxx** [comment]
Thanks to @xxchan for helping. The bug might be introduced by #12276 .

**Comment by MrCroxx** [comment]
`cargo tree -d` got:

```
[build-dependencies]
├── foyer-workspace-hack v0.1.0 (https://github.com/mrcroxx/foyer?rev=41b1d39#41b1d393) (*)
└── workspace-hack v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/workspace-hack) (*)

tikv-jemalloc-sys v0.5.4+5.3.0-patched (https://github.com/risingwavelabs/jemallocator.git?rev=64a2d9#64a2d988)
[build-dependencies]
└── workspace-hack v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/workspace-hack) (*)

tikv-jemalloc-sys v0.5.4+5.3.0-patched (https://github.com/risingwavelabs/jemallocator.git?rev=64a2d9#64a2d988)
├── tikv-jemalloc-ctl v0.5.4 (https://github.com/risingwavelabs/jemallocator.git?rev=64a2d9#64a2d988)
│   └── risingwave_compute v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/compute) (*)
├── tikv-jemallocator v0.5.4 (https://github.com/risingwavelabs/jemallocator.git?rev=64a2d9#64a2d988)
│   ├── risingwave_cmd v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/cmd) (*)
│   ├── risingwave_cmd_all v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/cmd_all)
│   └── risingwave_simulation v0.1.0 (/home/mrcroxx/github/risingwavelabs/risingwave/src/tests/simulation)
│   [dev-dependencies]
│   └── risingwave_batch v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/batch) (*)
└── workspace-hack v1.1.0-alpha (/home/mrcroxx/github/risingwavelabs/risingwave/src/workspace-hack) (*)
```

**Comment by MrCroxx** [comment]
https://github.com/risingwavelabs/risingwave/pull/12307

**Comment by xxchan** [comment]
The duplicated versions are with and without feature `unprefixed_malloc_on_supported_platforms`, which is `target.'cfg(unix)'.dependencies`.

I guess it's because the `build-dependency` (introduced by hakari) doesn't contain this feature.

We can see cargo does not unify features for `dependencies` and `build-dependencies`

```
[dependencies]
rand = { version = "0.8.5", default-features = false }

[build-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["serde"] }


❯ cargo tree -p rand -e features -i              
rand v0.8.5
└── tmp v0.1.0 (/private/tmp/tmp)
    └── tmp feature "default" (command-line)

rand v0.8.5
└── rand feature "serde"
    [build-dependencies]
    └── tmp v0.1.0 (/private/tmp/tmp) (*)
```

**Comment by xxchan** [comment]
If we add target in hakari config

https://github.com/risingwavelabs/risingwave/blob/214118baea97103207dfcd6e134a1e8fe63c31ad/.config/hakari.toml#L18

It will add new section

```toml
[target.x86_64-unknown-linux-gnu.dependencies]
...
tikv-jemalloc-sys = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", default-features = false, features = ["unprefixed_malloc_on_supported_platforms"] }
tikv-jemallocator = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
...

[target.x86_64-unknown-linux-gnu.build-dependencies]
...
tikv-jemalloc-sys = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", default-features = false, features = ["unprefixed_malloc_on_supported_platforms"] }
tikv-jemallocator = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
...
```

**Comment by xxchan** [comment]
Alternatively, this also exclude it from hakari

```diff
diff --git a/.config/hakari.toml b/.config/hakari.toml
index e998f5fea..9cdfbb3b0 100644
--- a/.config/hakari.toml
+++ b/.config/hakari.toml
@@ -35,6 +35,4 @@ third-party = [
     { name = "criterion" },
     { name = "console" },
     { name = "similar" },
-    # FYI: https://github.com/risingwavelabs/risingwave/issues/12315
-    { name = "tikv-jemalloc-sys", git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9" },
 ]
diff --git a/src/compute/Cargo.toml b/src/compute/Cargo.toml
index 24d12151c..6e3f8674a 100644
--- a/src/compute/Cargo.toml
+++ b/src/compute/Cargo.toml
@@ -39,7 +39,6 @@ risingwave_storage = { workspace = true }
 risingwave_stream = { workspace = true }
 serde = { version = "1", features = ["derive"] }
 serde_json = "1"
-tikv-jemalloc-ctl = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9" }
 tokio = { version = "0.2", package = "madsim-tokio", features = [
     "rt",
     "rt-multi-thread",
@@ -54,6 +53,10 @@ tonic = { workspace = true }
 tower = { version = "0.4", features = ["util", "load-shed"] }
 tracing = "0.1"
 
+[target.'cfg(unix)'.dev-dependencies]
+tikv-jemalloc-ctl = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9" }
+
+
 [target.'cfg(not(madsim))'.dependencies]
 workspace-hack = { path = "../workspace-hack" }
 
diff --git a/src/tests/simulation/Cargo.toml b/src/tests/simulation/Cargo.toml
index 82992b8b0..01c20b172 100644
--- a/src/tests/simulation/Cargo.toml
+++ b/src/tests/simulation/Cargo.toml
@@ -46,11 +46,14 @@ serde_derive = "1.0.188"
 serde_json = "1.0.107"
 sqllogictest = "0.15.3"
 tempfile = "3"
-tikv-jemallocator = { workspace = true }
 tokio = { version = "0.2.23", package = "madsim-tokio" }
 tokio-postgres = "0.7"
 tracing = "0.1"
 tracing-subscriber = { version = "0.3", features = ["env-filter"] }
 
+[target.'cfg(unix)'.dev-dependencies]
+tikv-jemallocator = { workspace = true }
+
+
 [lints]
 workspace = true

```

**Comment by xxchan** [comment]
> By default, cargo hakari produces the minimal set of features that can be unified across all possible platforms. However, in practice, most developers on a codebase use one of a few platforms. cargo hakari can run specific queries for a few platforms, producing better results for them.

**Comment by MrCroxx** [comment]
@xxchan Seems we can finally close this issue via #12333 ?

**Comment by MrCroxx** [comment]
@xxchan 

```toml
[target.x86_64-unknown-linux-gnu.dependencies]
axum = { version = "0.6" }
memchr = { version = "2" }
mime_guess = { version = "2" }
miniz_oxide = { version = "0.7", default-features = false, features = ["with-alloc"] }
once_cell = { version = "1", features = ["unstable"] }
openssl-sys = { version = "0.9", default-features = false, features = ["vendored"] }
opentelemetry = { version = "0.20", default-features = false, features = ["metrics", "rt-tokio", "trace"] }
opentelemetry_sdk = { version = "0.20", default-features = false, features = ["rt-tokio"] }
rdkafka-sys = { git = "https://github.com/MaterializeInc/rust-rdkafka", rev = "8ea07c4", default-features = false, features = ["cmake-build", "gssapi", "libz", "ssl-vendored", "zstd"] }
rustix = { version = "0.38", features = ["fs", "termios"] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
serde_json = { version = "1", default-features = false, features = ["raw_value"] }
tikv-jemalloc-sys = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
tikv-jemallocator = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
tower-http = { version = "0.4", features = ["add-extension", "cors", "fs"] }
zstd-sys = { version = "2", features = ["std"] }

[target.x86_64-unknown-linux-gnu.build-dependencies]
axum = { version = "0.6" }
memchr = { version = "2" }
mime_guess = { version = "2" }
miniz_oxide = { version = "0.7", default-features = false, features = ["with-alloc"] }
once_cell = { version = "1", features = ["unstable"] }
openssl-sys = { version = "0.9", default-features = false, features = ["vendored"] }
opentelemetry = { version = "0.20", default-features = false, features = ["metrics", "rt-tokio", "trace"] }
opentelemetry_sdk = { version = "0.20", default-features = false, features = ["rt-tokio"] }
rdkafka-sys = { git = "https://github.com/MaterializeInc/rust-rdkafka", rev = "8ea07c4", default-features = false, features = ["cmake-build", "gssapi", "libz", "ssl-vendored", "zstd"] }
rustix = { version = "0.38", features = ["fs", "termios"] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
serde_json = { version = "1", default-features = false, features = ["raw_value"] }
tikv-jemalloc-sys = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
tikv-jemallocator = { git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }
tower-http = { version = "0.4", features = ["add-extension", "cors", "fs"] }
zstd-sys = { version = "2", features = ["std"] }
```

`tikv-jemalloc-sys` duplicated again. 🥹
