### ISSUE TITLE
Use standalone-mode for all integration tests.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13307]
Previously, we made all integration tests running RW components individually. Let's use the standalone mode to further reduce the start time and add more testing to it.

```yaml
  compactor-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: compactor-0
  compute-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: compute-node-0
  frontend-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: frontend-node-0
  meta-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: meta-node-0
```

```yaml
  risingwave:
    extends:
      file: ../../docker/docker-compose-standalone.yml
      service: risingwave

```
