### ISSUE TITLE
alternative auth methods for kinesis source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13563]
### Describe the bug

Some users complained that we require ak/sk for authentication only, and they wondered if we support approaches like k8s Service Account or arn/session_token to access kinesis without exposing credentials. 

```yaml
  - name: aws.credentials.access_key_id
    field_type: Option < String >
    required: false
    alias: kinesis.credentials.access
  - name: aws.credentials.secret_access_key
    field_type: Option < String >
    required: false
    alias: kinesis.credentials.secret
```

On the other hand, I indeed noticed that our `access_key_id` and `secret_access_key` are optional fields. Therefore, it seems we do provide other ways to set up a connection. @tabVersion Please help check the details and then we'll correct the document, which marks these two fields as required. https://docs.risingwave.com/docs/current/ingest-from-kinesis/
