### ISSUE TITLE
compactor DeleteObjects return 405 with s3-compatible seaweedfs 

### ISSUE THREAD

**Issue by dramer-817** [risingwavelabs/risingwave#14076]
### Describe the bug

compactor DeleteObjects failed with return code 405 while meta success, because missing resource bucket in compactor request path

s3 config:
-------------
stateStore:
   dataDirectory: risingwave/hummock001
   s3:
     endpoint: mydomain.com
     bucket: rw-s3-dev
     region: us-east-1
     credentials:
       secretName: s3-credentials

request will to https://rw-s3-dev.mydomain.com

### Error message/log

```text
172.16.1.1 - - [20/Dec/2023:01:35:50 +0000] "POST /?delete&x-id=DeleteObjects HTTP/1.1" 405 0 "-" "aws-sdk-rust/1.0.1 os/linux lang/rust/1.75.0-nightly"
172.16.1.3 - - [20/Dec/2023:01:35:50 +0000] "PUT /risingwave/hummock001/checkpoint/0?x-id=PutObject HTTP/1.1" 200 0 "-" “aws-sdk-rust/1.0.1 os/linux lang/rust/1.75.0-nightly”
```

### To Reproduce

compactor running

### Expected behavior

return code 200 with object deleted success

### How did you deploy RisingWave?

kubernetes with operator

### The version of RisingWave

1.5.0

### Additional context

there is other with 405 

172.16.1.2 - - [20/Dec/2023:02:30:28 +0000] "PUT /?lifecycle HTTP/1.1" 405 0 "-" "aws-sdk-rust/0.55.3 os/linux lang/rust/1.75.0-nightly"

**Comment by wcy-fdu** [comment]
Hi @dramer-817 , we noticed that you are using seaweedfs as the remote object storage. We support s3-compatible storage, but not every storage is very compatible with s3, so I think this error may lie in seaweedfs. I don’t know if you have other alternative object storage options?

**Comment by dramer-817** [comment]
hi @wcy-fdu thank you for your response, i will try with minio later but it nice if seaweedfs supported too. 


Additional info, i tried with aws s3api cli and success

```
aws --profile seaweedfs-rw --endpoint-url https://rw-s3-dev.mydomain.com/ s3api delete-objects --bucket risingwave --delete file://delete-rw.json
{
   "Deleted": [
       {
           "Key": "hummock001/255/1.data"
       }
   ]
}
```

delete-rw.json:
```
{
 "Objects": [
   {
     "Key": "hummock001/255/1.data"
   }
 ],
 "Quiet": false
}
```
nginx log:
```
10.1.0.2 - - [20/Dec/2023:08:39:29 +0000] "POST /risingwave?delete HTTP/1.1" 200 162 "-" "aws-cli/2.14.5 Python/3.11.6 Linux/6.6.7-1-MANJARO source/x86_64.manjaro.23 prompt/off command/s3api.delete-objects"
```
there is bucket name in post request path

**Comment by dramer-817** [comment]
it seems seaweedfs works with config stateStore use minio
```
stateStore:
    dataDirectory: hummock
    # Declaration of the MinIO state store backend.
    minio:
      # Endpoint of the MinIO service.
      # endpoint: 172.16.1.11:9000
      endpoint: https://rw-s3-dev.mydomain.com
      
      # Name of the MinIO bucket.
      bucket: risingwave
      
      # Credentials to access the MinIO bucket.
      credentials:
        # Name of the Kubernetes secret that stores the credentials.
        secretName: s3-credentials
        
        # Key of the username ID in the secret.
        usernameKeyRef: username
        
        # Key of the password key in the secret.
        passwordKeyRef: password
```
nginx log:
```
172.16.1.1 - - [21/Dec/2023:07:21:59 +0000] "POST /risingwave/?delete&x-id=DeleteObjects HTTP/1.1" 200 211 "-" "aws-sdk-rust/1.0.1 os/linux lang/rust/1.75.0-nightly"
```
the objects got deleted, but still **?lifecyle** not return 200 with minio or seaweedfs with minio config, maybe it's ok
