### ISSUE TITLE
enable clippy lints for potential stack overflow & fix them

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#21635]
Under `[workspace.lints.clippy]` in `Cargo.toml`:

```toml
large_futures = "warn"
large_stack_arrays = "warn"
large_stack_frames = "warn"
large_types_passed_by_value = "warn"
```

Can help issues like
- #21335
- https://github.com/risingwavelabs/risingwave/issues/21427
- https://github.com/risingwavelabs/risingwave/issues/19906
