### ISSUE TITLE
riselab: add s3 support

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#34]
Basically there are two ways to support it:

```
    - use: compute-node
      port: 5689
      exporter-port: 1224
      state-backend: s3://bucket
```

If using the above way, we will need to add `state-backend` parameter to every compute-node. In some cases, we need to write it 3 times.

Another way is to make `s3` as a mock service.

```
  default:
    - use: s3
       bucket: xxxx
    - use: meta-node
    - use: compute-node
    - use: prometheus
    - use: frontend
```

... and for compute-node:

```
  compute-node:
    address: "127.0.0.1"
    port: 5688
    exporter-address: "127.0.0.1"
    exporter-port: 1222
    id: compute-node-${port}
    provide-minio: "minio*"
    provide-meta-node: "meta-node*"
+   provide-s3: "s3*"
    user-managed: false
```
