### ISSUE TITLE
panic: order of local synced ssts is not preserved in the global inserted sst

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5157]
### Describe the bug

In my environment, the computer nodes run for 15min and then all crashed due to same reason:

```
thread 'risingwave-main' panicked at 'order of local synced ssts is not preserved in the global inserted sst. local ssts: [2478, 2663], global: [2649, 2492, 2654, 2621, 2663, 2478]', src/storage/src/hummock/local_version.rs:481:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::local_version::LocalVersion::apply_version_delta_local_related
             at ./src/storage/src/hummock/local_version.rs:481:25
   3: risingwave_storage::hummock::local_version::LocalVersion::set_pinned_version
             at ./src/storage/src/hummock/local_version.rs:256:45
   4: risingwave_storage::hummock::local_version_manager::LocalVersionManager::try_update_pinned_version
             at ./src/storage/src/hummock/local_version_manager.rs:317:30
   5: <risingwave_compute::compute_observer::observer_manager::ComputeObserverNode as risingwave_common_service::observer_manager::ObserverNodeImpl>::handle_notification
             at ./src/compute/src/compute_observer/observer_manager.rs:57:17
   6: risingwave_common_service::observer_manager::ObserverManager<T>::start::{{closure}}::{{closure}}
             at ./src/common/common_service/src/observer_manager.rs:99:25
```

Full logs: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9502229/risingwave-log.tgz)

### To Reproduce

1. Modify `risedev.yml` and add this profile:

```
  full-3cn:
    - use: minio
    - use: etcd
    - use: meta-node
    - use: compute-node
      port: 5687
      exporter-port: 1222
    - use: compute-node
      port: 5688
      exporter-port: 1223
    - use: compute-node
      port: 5689
      exporter-port: 1224
    - use: frontend
    - use: compactor
    - use: prometheus
    - use: grafana
    - use: zookeeper
      persist-data: true
    - use: kafka
      persist-data: true
```

2. Start the cluster with `./risedev d full-3cn`
3. Create sources:

```
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

4. Create MView:

```
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

### Expected behavior

Don't crash

### Additional context

Full logs: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9502229/risingwave-log.tgz)
