### ISSUE TITLE
Grafana: node CPU usage numbers are too large

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#5851]
### Describe the bug

<img width="692" alt="image" src="https://user-images.githubusercontent.com/35356271/195787146-579f4eb9-bf75-45f8-9cbf-fa6f1c79bdf3.png">

**Comment by BowenXiao1999** [comment]
Can also show how to reproduce it?

**Comment by cyliu0** [comment]
> Can also show how to reproduce it?

@BowenXiao1999 I found this one when I investigated a resource-consuming issue. Basically, I created a table w/ only one column w/ 1 million rows and then create an MV on it.
But I think anything that could possibly consume CPU resources will end up like this.

**Comment by BowenXiao1999** [comment]
> Basically, I created a table w/ only one column w/ 1 million rows and then create an MV on it.

Are all the rows already inserted or being inserting when create the subsequent MV? Sounds like a Mv On MV problem. cc @BugenZhao, is this normal?

**Comment by BugenZhao** [comment]
I think this is a pure metrics issue, as the logic for stating CPU usage is highly customized by us. 😄 BTW, what's the system configuration when producing this?

cc @Little-Wallace @tabVersion

**Comment by cyliu0** [comment]
> I think this is a pure metrics issue, as the logic for stating CPU usage is highly customized by us. 😄 BTW, what's the system configuration when producing this?

It's just a 3 compute node setup on my laptop.

**Comment by cyliu0** [comment]
The risedev config in case you need it.
```
  full-3cn:
    - use: minio
    - use: etcd
    - use: meta-node
    - use: compute-node
      port: 5687
      exporter-port: 1222
    - use: compute-node
      port: 5688
      exporter-port: 1223
    - use: compute-node
      port: 5689
      exporter-port: 1224
    - use: frontend
    - use: compactor
    - use: prometheus
    - use: grafana
    - use: zookeeper
      persist-data: true
    - use: kafka
      persist-data: true
```
