### ISSUE TITLE
storage: store state store url in meta node and let compute and compactor node obtain it with RPC

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#7269]
### Is your feature request related to a problem? Please describe.

We will introduce Java binding in the near future, which will use hummock interfaces to read data. To create a hummock storage, we need its URL. Currently, this URL is passed to compute and compactor node through command-line arguments, which is in most cases, derived from risedev. This approach has two problems:

- Java binding should be independent of risedev, so there's no way to get this URL apart from passing it manually.
- State store URL is supposed to be consistent among all nodes in the cluster, but it is not guaranteed. Currently, if I `risdev d` with the bellow config:

```yml
- use: meta-node
- use: compute-node
- use: frontend

# If you want to enable compactor, uncomment the following line, and enable either minio or aws-s3 as well.
- use: compactor
```

The compute node and compactor will use two different object stores, because compute will use embedded object store, while compactor node will use `SHARED` in-memory object store. Querying the URL from meta naturally solves this problem.

### Describe the solution you'd like

Create an RPC at meta node to export state store URL.
