### ISSUE TITLE
panicked at 'attempt to divide by zero' at consistent_hash/mapping.rs

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#8190]
### Describe the bug

```
thread 'risingwave-main' panicked at 'attempt to divide by zero', src/common/src/hash/consistent_hash/mapping.rs:75:31                                                                                                                                                                                                                                                                    stack backtrace:                                                                                                                                                                                                                                                                                                                                                                             0: rust_begin_unwind                                                                                                                                                                                                                                                                                                                                                                                at ./rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:575:5                                                                                                                                                                                                                                                                                          1: core::panicking::panic_fmt                                                                                                                                                                                                                                                                                                                                                                       at ./rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:64:14                                                                                                                                                                                                                                                                                         2: core::panicking::panic                                                                                                                                                                                                                                                                                                                                                                           at ./rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:114:5                                                                                                                                                                                                                                                                                         3: risingwave_common::hash::consistent_hash::mapping::VnodeMapping<T>::new_uniform                                                                                                                                                                                                                                                                                                                  at ./risingwave/src/common/src/hash/consistent_hash/mapping.rs:75:31                                                                                                                                                                                                                                                                                                            4: risingwave_common::hash::consistent_hash::mapping::VnodeMapping<risingwave_common::hash::consistent_hash::mapping::marker::ParallelUnit>::build                                                                                                                                                                                                                                                  at ./risingwave/src/common/src/hash/consistent_hash/mapping.rs:299:9                                                                                                                                                                                                                                                                                                            5: risingwave_meta::stream::stream_graph::schedule::Scheduler::new                                                                                                                                                                                                                                                                                                                                  at ./risingwave/src/meta/src/stream/stream_graph/schedule.rs:239:36                                                                                                                                                                                                                                                                                                             6: risingwave_meta::stream::stream_graph::actor::ActorGraphBuilder::new                                                                                                                                                                                                                                                                                                                             at ./risingwave/src/meta/src/stream/stream_graph/actor.rs:611:29                                                                                                                                                                                                                                                                                                                7: risingwave_meta::rpc::ddl_controller::DdlController<S>::build_stream_job::{{closure}}                                                                                                                                                                                                                                                                                                            at ./risingwave/src/meta/src/rpc/ddl_controller.rs:351:13                                                                                                                                                                                                                                                                                                                       8: risingwave_meta::rpc::ddl_controller::DdlController<S>::create_streaming_job::{{closure}}                                                                                                                                                                                                                                                                                                        at ./risingwave/src/meta/src/rpc/ddl_controller.rs:233:17                                                                                                                                                                                                                                                                                                                       9: risingwave_meta::rpc::ddl_controller::DdlController<S>::run_command::{{closure}}::{{closure}}                                                                                                                                                                                                                                                                                                    at ./risingwave/src/meta/src/rpc/ddl_controller.rs:135:74                                                                                                                                                                                                                                                                                                                      10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll                                                                                                                                                                                                                                                                                                                     at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9                                                                                                                                                                                                                                                                               11: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}                                                                                                                                                                                                                                                                                                                                         at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17                                                                                                                                                                                                                                                                         12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut                                                                                                                                                                                                                                                                                                                                           at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9                                                                                                                                                                                                                                                                        13: tokio::runtime::task::core::Core<T,S>::poll                                                                                                                                                                                                                                                                                                                                                      at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panic/unwind_safe.rs:271:9
```

### To Reproduce

1. Using the following docker compose to deploy risingwave:
```
version: '2'
services:
  compute-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compute-node
      - "--host"
      - "0.0.0.0:5688"
      - "--client-address"
      - "compute-node-0:5688"
      - "--metrics-level"
      - "1"
      - "--state-store"
      - "hummock+memory-shared"
      - "--meta-address"
      - "http://meta-node-0:5690"
    expose:
      - "5688"
      - "1222"
    ports: []
    depends_on:
      - meta-node-0
    volumes:
      - "compute-node-0:/filecache"
    environment:
      RUST_BACKTRACE: "1"
    container_name: compute-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5688
      interval: 1s
      timeout: 5s
      retries: 5
  etcd-0:
    image: "quay.io/coreos/etcd:latest"
    command:
      - /usr/local/bin/etcd
      - "--listen-client-urls"
      - "http://0.0.0.0:2388"
      - "--advertise-client-urls"
      - "http://etcd-0:2388"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2389"
      - "--initial-advertise-peer-urls"
      - "http://etcd-0:2389"
      - "--listen-metrics-urls"
      - "http://0.0.0.0:2379"
      - "--name"
      - risedev-meta
      - "--max-txn-ops"
      - "999999"
      - "--auto-compaction-mode"
      - periodic
      - "--auto-compaction-retention"
      - 1m
      - "--snapshot-count"
      - "10000"
    expose:
      - "2388"
    ports:
      - "2388:2388"
      - "2389:2389"
    depends_on: []
    volumes:
      - "etcd-0:/etcd-data"
    environment: {}
    container_name: etcd-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/2388
      interval: 1s
      timeout: 5s
      retries: 5
  frontend-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - frontend-node
      - "--host"
      - "0.0.0.0:4566"
      - "--client-address"
      - "frontend-node-0:4566"
      - "--metrics-level"
      - "1"
      - "--meta-addr"
      - "http://meta-node-0:5690"
    expose:
      - "4566"
    ports:
      - "4566:4566"
    depends_on:
      - meta-node-0
    environment:
      RUST_BACKTRACE: "1"
    container_name: frontend-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5
  
  meta-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--host"
      - meta-node-0
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports:
      - "5691:5691"
      - "5690:5690"
    depends_on: []
    environment:
      RUST_BACKTRACE: "1"
    container_name: meta-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5690
      interval: 1s
      timeout: 5s
      retries: 5
  
volumes:
  compute-node-0:
    external: false
  etcd-0:
    external: false
```

2. Use psql to create table:
```sql
create table t(a int);
```

### Expected behavior

_No response_

### Additional context

It worked when I use the image two weeks ago so it seems like a misconfugration due to some breaking changes.
