### ISSUE TITLE
bug: Madsim tonic doesn't support timeout method.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#8398]
### Describe the bug

See https://docs.rs/tonic/latest/tonic/transport/struct.Endpoint.html#method.timeout.

### To Reproduce

Just add this method in channel builder, and it can't compile in madsim.

### Expected behavior

Madsim should support this method.

### Additional context

I'm trying to add this method to help debug a hang issue.

**Comment by wangrunji0408** [comment]
You can add the following lines to the root `Cargo.toml` to enable this method:
```toml
[patch.crates-io]
madsim = { git = "https://github.com/madsim-rs/madsim.git", rev = "5734baa" }
madsim-tonic = { git = "https://github.com/madsim-rs/madsim.git", rev = "5734baa" }
```

I'll release a new version for madsim later if it works well.
