### ISSUE TITLE
bug: batch query uses wrong parallel unit after fragment rescheduling

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#8615]
### Describe the bug

After fragment rescheduling, a worker node contains no actor, but later batch query still [schedules task to its parallel unit](https://github.com/risingwavelabs/risingwave/blob/7b5ffb4ea4f3f8e52dcb7f5f92b4fa983b38259f/src/frontend/src/scheduler/distributed/stage.rs#L340) (and not to other correct parallel units), which fails the query.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/70626450/225822224-e8693a6c-69f3-46e3-a0ce-7cf919c14a75.png">

### To Reproduce

1. Add any log to print `parallel_unit_ids` [here](https://github.com/risingwavelabs/risingwave/blob/7b5ffb4ea4f3f8e52dcb7f5f92b4fa983b38259f/src/frontend/src/scheduler/distributed/stage.rs#L340).
2. Modify risedev.yml and `./risedev d for-ctl`
```
for-ctl:
    steps:
      - use: minio
      - use: meta-node
      - use: compute-node
        port: 5687
        exporter-port: 1222
        parallelism: 1
      - use: compute-node
        port: 5688
        exporter-port: 1223
        parallelism: 1
      - use: compute-node
        port: 5689
        exporter-port: 1224
        parallelism: 1
      - use: frontend
      - use: compactor
```
3. Create sources and mv. [sql.txt](https://github.com/risingwavelabs/risingwave/files/10998213/sql.txt)
4. Reschedule fragment to remove all actors from worker node 1: `./risedev ctl meta reschedule --plan "1-[0]+[1];2-[0];3-[0];4-[0]"`
<img width="581" alt="image" src="https://user-images.githubusercontent.com/70626450/225822224-e8693a6c-69f3-46e3-a0ce-7cf919c14a75.png">

5. `select * from nexmark_q106;`
6. Check frontend.log, find worker node 1's parallel unit is used unexpectedly.

```
2023-03-17T05:42:12.740589Z  INFO risingwave_frontend::scheduler::distributed::stage: [
    0,
] [
    WorkerNode {
        id: 1,
        r#type: ComputeNode,
        host: Some(
            HostAddress {
                host: "127.0.0.1",
                port: 5687,
            },
        ),
        state: Running,
        parallel_units: [
            ParallelUnit {
                id: 0,
                worker_node_id: 1,
            },
        ],
    },
]
```

### Expected behavior

Batch query should be scheduled to correct parallel unit.

### Additional context

Found [here](https://github.com/risingwavelabs/risingwave/pull/8292#issuecomment-1471658273), after we `SET visibility_mode=all`, hummock's seal_epoch check reveals this issue.
